version: '3.9'

services:
  postgres:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/initdb:/docker-entrypoint-initdb.d

  # redis:
  #   image: redis:7
  #   ports:
  #     - "6379:6379"

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"

  auth-service:
    build: ./auth-service
    depends_on:
      - postgres
      # - redis
    env_file:
      - ./auth-service/.env
    environment:
      - DB_DSN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/auth?sslmode=disable
      - PORT=8000
    ports:
      - "${AUTH_SERVICE_PORT}:8000"

volumes:
  pgdata:
